micronaut:
    application:
        name: mod-directory
---
# grails:
#     gorm:
#         multiTenancy:
#             mode: SCHEMA
#             tenantResolverClass: 'com.k_int.mn.okapi.OkapiTenantResolver'
---
datasources.default: {}
---
hibernate:
  hbm2ddl:
    auto: none
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
  pooled: true
  jmxExport: false
  dbCreate: none
  username: "${db.username:folio_admin}"
  password: "${db.password:folio_admin}"
  driverClassName: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  url: "jdbc:postgresql://localhost:54321/okapi_modules"
# schemaHandler: com.k_int.okapi.OkapiSchemaHandler
